services:
    db:
        image: mysql:5.7
        restart: always
        networks:
            slims-net:
                ipv4_address: 172.50.1.3
        container_name: slims-db
        env_file:
            - db_default.env
        command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_allowed_packet=1024M
        volumes:
            - db_data:/var/lib/mysql:rw
        ports:
            - "3306:3306"
    web:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        networks:
            slims-net:
                ipv4_address: 172.50.1.11
        container_name: slims-app
        user: $DOCKER_USER
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web_data:/home/developer/slims

    phpmyadmin:
        image: phpmyadmin
        links:
            - db
        networks:
            slims-net:
                ipv4_address: 172.50.1.12
        environment:
            PMA_HOST: db
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8080:80

volumes:
   db_data:
       driver: local # Define the driver and options under the volume name
       driver_opts:
          type: none
          device: /home/developer/slims/db
          o: bind
   web_data:
       driver: local # Define the driver and options under the volume name
       driver_opts:
          type: none
          device: /home/developer/slims/app
          o: bind
networks:
    slims-net:
        name: slims-net
        ipam:
            driver: default
            config:
              - subnet: "172.50.1.0/24"
